exclude: '^(venv/data)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --profile
          - black
          - --thirdparty
          - config
          - --thirdparty
          - milvus_db_utils
          - --check
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: requirements-txt-creator
        name: create requirements.txt from poetry.lock
        language: system
        pass_filenames: false
        entry: poetry export -f requirements.txt --without-hashes --output requirements.txt --only dev --without data
  - repo: local
    hooks:
      - id: requirements-txt-add
        name: git add requirements/requirements.txt
        language: system
        pass_filenames: false
        entry: git add requirements.txt
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        language: system
        pass_filenames: false
        entry: "pytest tests/u_tests_scrap_etrange_festival.py"
  - repo: https://github.com/dhatim/python-license-check
    rev: master
    hooks:
      - id: liccheck
        language: system
